version: "3"

services:

  server:
    container_name: server-crowd-sourced
    build: ./server
    restart: always
    volumes: 
      - './server:/app'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=crowd-sourced
    ports:
      - "8080:8080"

  client:
    container_name: client-crowd-sourced
    build: 
      context: ./client
    stdin_open: true
    restart: always
    volumes:
      - "./client:/App"
      - "./client/node_modules:/App/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - "server"

  mongo:
    container_name: mongodb-crowd-sourced
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SGG
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null      
    volumes:
      - "./data/mongodb:/data/db"
    ports:
      - "27017:27017"
    